### ISSUE TITLE
Custom Study with "mark" clozes

### ISSUE THREAD

**Issue by lucasndv** [glutanimate/cloze-overlapper#11]
Hi Glut!
I'm searching a solution for custom study for cloze overlapper 

The problem is:
Is there a way to create a custom study for the clozes i've marked?
Because when i "mark" a card, anky "mark" all the clozes, i only want the specific ones

Here is an exemple

Question1
[oc1::Asw1] (i need to MARK it/Specif Tag )

Question2
[oc2::Asw2]

Question3
[oc3::Asw3]
.
Etc..

**Comment by glutanimate** [comment]
Hey Lucas,

It's been a while, but just in cause you're still interested in this: Anki 2.1 now comes with the ability to flag individual cards (flags behave like marks, only that the pertain to one card rather than the entire note). I'm not 100% certain about this, but I think you should be able to construct a filtered deck / custom study session from those flags. However, you'd best ask on the [Anki support forums](https://anki.tenderapp.com/) to be sure.

Hope that helps!

(Closing this as it's a general issue with Anki rather than something pertaining to the add-on specifically)
