### ISSUE TITLE
How to update notes?

### ISSUE THREAD

**Issue by Alok** [glutanimate/cloze-overlapper#4]
I notice a typo in a cloze note, so I update it. Except that the `Text1`,`Text2`, etc. fields do not update to reflect that change. Can I force them to update?

**Comment by glutanimate** [comment]
The notes will update automatically when editing them while reviewing. In the Browser you will have to click on this button to instruct the add-on to regenerate the fields:

 ![](https://raw.githubusercontent.com/wiki/glutanimate/cloze-overlapper/screenshots/button-generate.png)

The lack of automation in the Browser is something I'd like to address in the future, but due to limitations of how the Editor widget works it seems like there is no viable way to implement this properly at this point.

For a full overview of the editing options make sure to check out the tutorial video, [starting from 16:25](https://www.youtube.com/watch?v=ag4Hdnkig8U&feature=youtu.be&t=985).
